### ISSUE TITLE
AccMgmt | Oppdatere Delegations API for skriving av From/To/PerformedBy

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization-tmp#170]
### Description

Det interne Delegations API'et i AccessManagement som benyttes fra Altinn 2 for export av delegeringer fra Altinn 2 til migrerte ressurser i Altinn 3 + ved godkjenning av "be om tilgang" forespørsler som inneholder Altinn 3 Apps, må oppdateres med støtte for å også skrive til de nye From/To/PerformedBy kolonnene i databasen.

OfferedByPartyId => From
CoveredBy => To
DelegatedByUserId/DelegatedByPartyId => PerformedBy

Uten dette vil det ikke være mulig å standardisere alle fremtidige oppslag basert på uuids.

### Additional Information

Delegations API er implementert i DelegationsController og brukes fra Altinn 2. A2 autentiserer seg med et PlatformToken med app-claim: sbl.authorization

### Tasks

- [ ] Utvide testTokenGenerator script for å kunne ta imot token av type "Platform"
- [ ] Oppdatere AddRules API endepunkt: `accessmanagement/api/v1/delegations/addrules`
- [ ] Oppdatere DeleteRules API endepunkt: `accessmanagement/api/v1/delegations/deleterules`
- [ ] Oppdatere DeletePolicy API endepunkt: `accessmanagement/api/v1/delegations/deletepolicy`
- [ ] Lage automatiserte Bruno tests

### Acceptance Criterias

- [ ] **AC-1: AddRule for A3 App**
SOM Altinn 2
NÅR AddRules blir kallet på (fra Be om tilgang) for delegering av regler for Altinn 3 App
SÅ skal delegeringen bli lagret i databasen med UUID'er for From/To/PerformedBy for delegeringen

- [ ] **AC-2: AddRule for A3 Ressurs**
SOM Altinn 2
NÅR AddRules blir kallet på (fra batchjob for migrering av delegeringer) for delegering av regler for Altinn 3 Ressurs
SÅ skal delegeringen bli lagret i databasen med UUID'er for From/To/PerformedBy for delegeringen

### Test

- [ ] AC-1 : Verifisere delegering blir lagret med UUID for From/To/PerformedBy for delegeringen når delegering er godkjent for Altinn3 App
- [ ] AC-2 : Verifisere delegering blir lagret med UUID for From/To/PerformedBy for delegeringen når AddRules blir kallet på (fra batchjob for migrering av delegeringer)

**Comment by sneha-sirure** [comment]
@Siri-Anna @rtafj @howieandersen Da har jeg verifisert denne i AT22 og lukker tasken.
