### ISSUE TITLE
Tilgangspakker | Metadata API - Implementering

### ISSUE THREAD

**Issue by Thuen** [Altinn/altinn-authorization-tmp#285]
Få løsningen opp og kjøre. 

- [x] Skal gå å kjøre opp lokalt
- [ ] ~Kjøres opp selvstendig på nytt miljø~
- [ ] Integreres i AccessMgmt løsning

```[tasklist]
### Tasks
 -[ ] https://github.com/orgs/Altinn/projects/50/views/1254
- [ ] https://github.com/Altinn/altinn-authorization/issues/1251
```
