### ISSUE TITLE
Move Panel for Klientdelegering from 2.0 to 3.0 

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization-tmp#328]
### Description

Panel for Klientdelegering and Connected views are to be moved from Altinn 2.0 and implementet in 3.0 designsystems and as react komponent in to 3.0 Altinn Authorization

The views are to be implemementet with same view and functionality as before

Data about employees clients and delegated roles will be fetched from the 2.0 plattfrom though a 3.0 API that collects thiis information from Altinn 2.0 via SBL-bridge. 

## Definisjoner
Klient - kunde hos regnskapsfører/revisor som har registrert knytning i Enhetsregisteret
ServiceProvider - regnskapsfører/revisor som er registrert på kunden i Enhetsregisteret
Klientadministrator - tilgangsstyringsrolle i Altinn for å kunne administrere tilgang for sine klienter til sine ansatte

### In scope

Panel for Klientdelegering: 
List of employees 
![image](https://user-images.githubusercontent.com/25847572/184317647-09230ce4-aefc-4f38-9e10-a7c7dd761ef1.png)

List of Clients
![image](https://user-images.githubusercontent.com/25847572/184319017-70d33d66-2604-4f46-a7ae-7d6e7ed048f6.png)

Change clients for eployee
![image](https://user-images.githubusercontent.com/25847572/184320454-84600373-d74b-43f8-b74d-cd23a702fefa.png)

Change employee for clients
![image](https://user-images.githubusercontent.com/25847572/184320563-17dd79f2-e30b-4677-b143-7adc3f05b790.png)

Add employee
Note: we wish to change icon for "ekstern virksomhet" to make it clearer that a enterprice can not be registered as an employee
![image](https://user-images.githubusercontent.com/25847572/184319713-c39dbb87-235a-4c63-80dd-9cfa62dbab45.png)

### Out of scope

Page for downlooad/uplod of clientdelegation by file
![image](https://user-images.githubusercontent.com/25847572/184320773-7e51b8d7-dd24-429d-926f-25854d0ed2ef.png)

```[tasklist]
### Features
- [ ] Klientdelegering | Legg til ny ansatt/person
- [ ] Klientdelegering | Delegere klientroller
- [ ] Klientdelegering | Slette klientdelegering
- [ ] Klientdelegering | Oversikt over klienter
- [ ] Klientdelegering | Oversikt over ansatte
- [ ] Klientdelegering | Skjule klienter som er slettet i ER fra klientdelegering
```

```[tasklist]
### Avklaringer
- [ ] 1. Skal klientdelegering på 3.0 støtte både tilgangspakker og Altinn-roller? **Svar**: Kun tilgangspakker
- [ ] 2. Delegering på fil erstattes av API for massedelegeringer? **Svar**: Ja
```

Tasks in 3.0.
Top to bottom priority list.

**Client delegation accordion content:** 
- [x] Implement react portals
- [x] Put together a demo view of klientdelegering
- [x] Create local component ListItem - Employees
- [ ] Create local component ListItem - Clients | Almost done
- [x] TextField - Add left and right icon - https://github.com/Altinn/altinn-design-system/issues/123
- [x] Combine all individual components to finish Accordion content Klientdelegering | On hold until this is finished: https://github.com/Altinn/altinn-access-management-frontend/issues/85

**"Endre rettigheter"-Page (More tasks will come in future):**
- [x] Create Page component in design system - https://github.com/Altinn/altinn-design-system/issues/57
- [ ] Make inverted buttons that can have icons (The buttons with <- and x). | On hold until team studio has implemented Quiet button.
- [x] Create local component for hiding/ showing clients | https://github.com/Altinn/altinn-access-management-frontend/issues/87
- [ ] Create Table comoponent that can sort name
- [ ] Integrate with backend

**"Legge til ny ansatt"-Page | on hold until UX breakdown is done**
- [ ]

**"Klientdelegering på fil"-Page | on hold until UX breakdown is done**
-[ ]

Tasks in 2.0 
(legg inn lenke til US i https://dev.azure.com/digdir
- [ ]
