### ISSUE TITLE
Tilgangspakker | Metadata API

### ISSUE THREAD

**Issue by Thuen** [Altinn/altinn-authorization-tmp#50]
# Tilgangspakker | Metadata API

## Beskrivelse
Dette er et åpent API som kun skal eksponere åpne data.

## Definisjoner
|Url|Description|
|-|-|
package/ | Gets all packages
package/{id} | Gets a single package
taggroup/ | Gets all tag groups
taggroup/{id}/tags | Gets all tags in a group
tag/ | Gets all tags
tag/{id} | Gets a single tag
role| Gets all roles
role/{id} | Gets a single role
role/{id}/mapping/policy | Gets all policy mappings for a single role
role/{id}/mapping/role | Gets all role mappings for a single role

## Modeller (Ikke forankret)
```json
<!--- Package --->
{
    "id": "",
    "name": "Nye bedrifter",
    "isdelegable": true,
    "tags": ["Bygg og anlegg", "Bransje"],
    "rolemapping": [
        { 
            "id":"", 
            "name":"DAGL", 
            "urn":"brreg:role:dagl",
            "candelegate": true,
            "hasaccess": false
        },
        { 
            "id":"", 
            "name":"HA", 
            "urn":"altinn:role:ha",
            "candelegate": true,
            "hasaccess": false
        }
    ]
}
```

```json
<!--- TagGroup --->
{
    "id": "",
    "name": "Område",
    "tags": [
        {
            "id":"",
            "name":"Bygg og anlegg",
            "groupid":""
        },
        {
            "id":"",
            "name":"Skatt, avgift, regnskap og toll",
            "groupid":""
        }
    ]
}
```

```json
<!--- Tag --->
{
    "id": "",
    "name": "Bygg og anlegg",
    "groupid": ""
}
```

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-authorization/issues/1116
- [ ] https://github.com/Altinn/altinn-authorization/issues/1117
- [ ] https://github.com/Altinn/altinn-authorization/issues/1118
```
