### ISSUE TITLE
API for å hente ut informasjon om samtykkeforspørsel

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization-tmp#580]
# Beskrivelse

Det må lages et API i AccessManagement som basert på en samtykkeforespørsel ID kan hente ut informasjon om et ønsket samtykke. 

Konsument av API vil være sluttbruker som kaller via Access Management BFF.  Data vil presenteres i samtykkeside. 

## Avklaringer

- Skal API sjekke om autentisert bruker har rettighet til og delegere rettighetene eller skal det gjøres i etterkant av BFF?

Forslag: Det gjøres i etterkant av BFF ved hjelp av en delegation check. Det synliggjøres i GUI hvilke tjeneste bruker eventuelt ikke har

## Design

Url /accessmanagement/api/v1/enduser/concent/{concentid}

Model 

```json

{
    "id": "b55b0a8c-46db-4239-a417-a89daabfabba",
    "from": "urn:altinn:organization:identifier-no:01039012345",
    "to": "urn:altinn:person:identifier-no:984851006",
    "requestmessage": {
        "nb": "Ved å samtykke, gir du Skatteetaten rett til å utlevere opplysninger om deg direkte til DNB BANK ASA. Banken får opplysningene for å behandle søknad om finansiering.",
        "nn": "Ved å samtykke, gir du Skatteetaten rett til å utlevere opplysningar om deg direkte til DNB BANK ASA. Banken får opplysningane for å behandle søknad om finansiering.",
        "en": "By consenting, you give the Tax Administration the right to disclose information about you directly to DNB BANK ASA. The bank receives the information to process the financing application."
      },
        "concentrights": [
        {
            "action": [
                "read",
                "write"
            ],
            "resource": [
                {
                    "id": "urn:altinn:resource",
                    "value": "skd_inntektsapi"
                }
            ],
            "metadata": {
                "fraOgMed": "2017-06",
                "tilOgMed": "2017-08"
            }
        },
        {
            "action": [
                "read",
                "write"
            ],
            "resource": [
                {
                    "id": "urn:altinn:resource",
                    "value": "skd_skattegrunnlag"
                }
            ],
            "metadata": {
                "inntektsaar": "2016"
            }
        }
    ],
    "PortalViewMode": "Hide"
} 

```

## Krav
- [ ] Input til å hente ut en forespørsel er en forespørsel ID
- [ ] Sikkerhetsnivå styres av sikkerhetsnivå på tjenesten. Minimum nivå 3 
- [ ] Det kreves skriverettighet til tilgangsstyring for å kunne se på et samtykke

# Task

- [ ] Definer egen kontrakt for request for sluttbruker API. (ikke samme modell som input på requeste, men kan være lik attributtmessig)
- [ ] Eksponer endepunkt. Path må følge Url mønster til access management
- [ ] Oppdater APIM

### Positivt scenario. Bruker henter ut informasjon om. 

**Forutsetning** For hvert av scenarioen må det sendes inn en samtykkeforespørsel som enten matcher eller ikke matcher med behovet. 

**Gitt** at en sluttbruker har skriverettighet til systemressursen og den oppgir referanse til en samtykkeforespørsel som matcher aktøren man har rettigheten til så skal API returnere informasjon om samtykket

Testtype: XUNIT unittest og integrasjonstest

### Negativt scenario 

**Gitt** at en sluttbruker oppgir en requestid som tilhører en annen part så skal man få 403 i respons

### For lavt sikkerhetsnivå

**Gitt** at en sluttbruker har skriverettighet til systemressursen og den oppgir referanse til en samtykkeforespørsel som matcher aktøren man har rettigheten men man er innlogget med for lavt sikkerhetsnivå så skal man bli avvist. 

- [ ] Test av sikkerhetsnivå.  Bruker for lavt sikkerhetsnivå. Får feilmelding

**Comment by Nyeng** [comment]
**Testscenarioer**

- Positivt scenario. Ok.
- 403 - Ok, får ikke lov til å hente forespørsel
- For lavt sikkerhetsnivå - 

**Negative testscenarioer**
- Teste ukjent samtykke-id - gir 404 og rendrer feilmelding til brukeren
