### ISSUE TITLE
Implementere ny samtykke side

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization-tmp#597]
# Beskrivelse

Ved overføringen til Altinn 3 samtykke må det utvikles nye samtykkesider for Altinn.

![Image](https://github.com/user-attachments/assets/d9e7dbf0-4c1f-4029-87c9-c5801e5388d0)

Samtykkesiden presenterer informasjon om den som ber om samtykke, hva samtykket skal brukes til og hva samtykket består av. 

Bruker kan basert på den informasjonen samtykke eller avvise samtykke. 

Etter samtykket er gitt eller avvist så skal bruker logges ut og redirectes til url som den som ba om samtykke oppga.

## Arkitektur

Hypotesen er.

- Siden utvikles som en feature i Access management frontend
- Nødvendige API eksponeres i Access Management BFF

Dette betyr at begge autorisasjonsteamene vil jobbe med samme applikasjoner. Må

## Krav
- [ ] Man må være pålogget for å kunne
- [ ] Man skal åpne samtykkesiden med referanse til en samtykkeforespørsel. 
- [ ] Samtykkesiden må sjekke om bruker er autorisert for å se samtykkeforspørsel. 
- [ ] Samtykkesiden krever tilgangstyring for å kunne se
- [ ] Samtykke siden skal følge malen som er knyttet mot sam
- [ ] Detaljer om samtykke ressurs skal vises
- [ ] Sluttbruker må autoriseres for hver enkelt ressurs om han har rettighet til å gi samtykket til de aktuelle ressursene 

## Task
- [ ] Utvikle Concent feature i Access managment frontend
- [ ] Utvide BFF med nødvendige API for å vise og bekrefte samtykke

### Testscenario 1: Åpne samtykke for avgiver hvor sluttbruker er autorisert for se og godkjenne samtykke

- Mulig å åpne en samtykkeforespørsel basert på gyldig URL 
-
