### ISSUE TITLE
Godkjenne samtykke

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authorization-tmp#602]
## Beskrivelse

Som sluttbruker skal man kunne godkjenne en samtykkeforespørsel for en avgiver man er autorisert for.

Datakonsumenten som ber om samtykke vil i første leveranse være den som gir redirecter (http 302) til url hvor samtykkeforespørsel kan studeres. 

## Krav
- [ ] Godkjenning av samtykke er kun tilgjengelig via GUI. Det skal ikke være tilgjengelig via API
- [ ] Datakonsument har opprettet samtykkeforspørsel og hentet ut url for å presentere samtykkeforpørsel som brukes for å åpne siden for å bekrefte
- [ ] Sluttbruker skal bli presentert informasjon om hvem som ber om samtykke
- [ ] Sluttbruker skal autoriseres for å kunne se samtykke og for å kunne gi samtykke. Krever tilgangstyringsrettighet samt rettighet for tjenesten som datakonsumentet ber om samtykke for. 
- [ ] Når samtykke gis skal det logges informasjon om hvem som ga samtykke og tidspunkt
- [ ] Status på samtykkeforespørsel skal oppdateres
- [ ] Design på inneholde design på feilmeldinger når man ikke er autorisert for å samtykke

## Task

- [ ] Lage oppdatert design for samtykkeside
- [ ] Implementere API for samtykke informasjon
- [ ] Implementere API for å godkjenne samtykke
- [ ] Implementere API for å avvise samtykke
- [ ] Impementere GUI for 

## Avklaringer
- Skal man kunne se informasjon om samtykkeforespørselen selv om man ikke har rettighet til å gi samtykket. Antakelse er nei. Bruker blir bare informert om at han ikke har nødvendige rettigheter for å samtykke. Sjekk med Jus

### Testscenario 1 - Sluttbruker er autorisert til avgiver og har nødvendige rettigheter

- Bruker har tilgangstyringrettighet og har rettighet til å delegere ressursene som samtykkeforspørselen består av
- Bruker har muliget til å trykke "Gi samtykke" 
- Bruker blir logget ut av ID-porten 
- Bruker blir redirectet til url som datakonsument har oppgitt i samtykkeforespørsel

### Testscenario 2 - Sluttbruker er autorisert for avgiver tilgangstyring men mangler rettigheter

- Bruker har tilgangstyrer for avgiver
- Bruker mangler rettigheter for tjenesten. 
- Bruker skal bli avvist.

### Testscenario 3 - Avansert samtykkeforspørsel med flere ressurser og med parametere

- Bruker har tilgangstyringrettighet og har rettighet til å delegere ressursene som samtykkeforspørselen består av
- Bruker har muliget til å trykke "Gi samtykke" 
- Sluttbruker blir presentert informasjon om parametere som er med i samtykkeforespørsel.
- Sluttbruker blir presentert detaljer om alle ressursene
- Sluttbruker blir presentert informasjonen på en slik måte at det matcher med samtykkemal

**Comment by ekorra** [comment]
Samtykke i prod 01.10.25
