### ISSUE TITLE
AccMgmt - Ny systemressurs og autorisasjonspolicy for tilgangsstyring i Enduser API

### ISSUE THREAD

**Issue by andreasisnes** [Altinn/altinn-authorization-tmp#96]
# Beskrivelse

For å implementere funksjonaliteten i #95, trenger vi et ActionFilter som sørger for å populere HttpContext med sluttbrukerens rolle for en valgt avgiver. Filteret skal bruke brukerens ID fra tokenet til å slå opp sluttbrukerens rolle i ER-registeret. Avgiveren er ikke tilgjengelig i tokenet, men den kan hentes fra query parameteren Party, som spesifisert i [Swagger-dokumentasjonen](https://app.swaggerhub.com/apis/jon.kjetil.oye/AccessManagementInstanceDelegation/1.0#/Enduser%20Access/get_accessmanagement_api_v1_enduser_access_recipients).

Filteret skal implementeres ved å bruke IActionFilter, og i metoden OnActionExecuting må følgende logikk inkluderes:

* Lese og validere query parameteren Party. Parameteren forventes å eksistere ettersom filteret kjøres etter model binding, men hvis query param skulle mangle så skal forespørselen avbrytes med en `400 Bad Request` respons.
* Hvis avgiver ikke finnes blant brukerens avgivere skal `403 Forbidden` respons.
* Utføre autorisasjon av sluttbrukeren mot PEP for ny systemressurs brukerens ID i tokenet og avgiveren hentet fra Party-parameter.
* Ettersom autentiseringen allerede er fullført, skal resultat av PEP autorisasjon ikke legges under HttpContext.User, men i stedet lagres i HttpContext.Items med en definery Key. F.eks: "IsAccessManager". 

### Tasks
- [ ] Opprette ny AccessManagement systemressurs for sluttbrukere (lignende dagens altinn_access_management). A2 `ADMAI/HADM` rolle skal bare gi action: `les`, mens A3 `TS/HA` tilgangspakke skal gi `les` og `skriv`
- [ ] Gammel/eksisterende system-ressurs må oppdateres med at nye A3 `TS/HA` tilgangspakke skal gi `les` og `skriv`
- [ ] Implementere ActionFilter i henhold til logikk krav spesifisert over

#### AC1: Lesetilgang som A2 Tilgangsstyrer / Hovedadministrator 
SOM Tilgangsstyrer/Hovedadministrator i Altinn 2
NÅR jeg følger link til ny landingsside for Tilgangsstyring i Altinn 3
SÅ skal jeg bare få lese tilgang til Tilgangsstyringssidene og ikke kunne utføre delegering eller slette tilganger

#### AC2: Lese- og skrive-tilgang som A3 Tilgangsstyrer / Hovedadministrator
SOM Tilgangsstyrer/Hovedadministrator i Altinn 3
NÅR jeg følger link til ny landingsside for Tilgangsstyring i Altinn 3
SÅ skal jeg både få lese tilgang til Tilgangsstyringssidene og kunne utføre delegering eller slette tilganger

#### AC3: Lesetilgang til egne tilganger + oversikt over nøkkelpersoner
SOM Bruker som har tilgang til avgiveren
NÅR jeg følger link til ny landingsside for Tilgangsstyring i Altinn 3
SÅ skal jeg ha tilgang til å se og redigere mine egne tilganger
   OG jeg skal ha tilgang til å se oversikt over nøkkelpersoner i virksomheten

### Test

- [ ] AC-1 : Verfisere coveredby bruker får bare lesetilgang etter følger lenke til ny tilgangstyrring Altinn3 GUI når offeredby bruker som Tilgangstyrrer/HADM gir bare lesetilgang i Altinn2 
- [ ] AC-2 : Verfisere coveredby bruker får bare lese og skrive tilgang etter følger lenke til ny tilgangstyrring Altinn3 GUI når offeredby bruker som Tilgangstyrrer/HADM gir lese og skrive tilgang i Altinn2 
- [ ] AC-3 : Verifisere som bruker som har tilgang til avgiver har tilgang til å se og redigere egne tilganger og å se oversikt over søkkelpersoner i virksomheten når bruker følger opp lenke til ny landingside i altinn3

**Comment by jonkjetiloye** [comment]
@andreasisnes 
Ønsker ikke at vi skal duplisere autorisasjonslogikk. Så selve sjekken for å autorisere om bruker har lese eller skrive tilgang for tilgangsstyring i Altinn, så skal vi fortsatt bruke den eksisterende systemressursen (altinn_access_management) som sjekkes i dagens;
`[Authorize(Policy = AuthzConstants.POLICY_ACCESS_MANAGEMENT_READ)]`
 (hvor policy spesifierer rollekrav). 

Men ja vi trenger ett nytt action filter som ikke blokkerer tilgang til operasjonen om man ikke er tilgangsstyrer men i stedet legger resultatet i HttpContext. Slik at operasjonen selv kan switch-case internt på hvilket oppslag som skal gjøres.
